[versions]
axion = "1.18.16"
googleJavaFormat = "1.28.0"
javaCore = "8"
javaIntegrationTests = "17"
javaSpringBoot = "8"
javaSpringBootAdmin = "17"
jreleaser = "1.20.0"
siouanFrontend = "6.0.0"
spotless = "8.2.1"
springBoot27 = "2.7.18"
springBoot35 = "3.5.11"
springBoot40 = "4.0.3"
springBootAdmin = "4.0.1"

[libraries]
siouanFrontend-gradlePlugin = { module = "org.siouan:frontend-gradle-plugin-jdk11  ", version.ref = "siouanFrontend" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
springBoot27 = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot27" }
springBoot35 = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot35" }
springBoot40 = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot40" }
springBootAdmin = { group = "de.codecentric", name = "spring-boot-admin-dependencies", version.ref = "springBootAdmin" }

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion"}
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot40" }
